export type ProductCategory =
  | "lapel-pin"
  | "keychain"
  | "card-sticker"
  | "fridge-magnet"
  | "earring"
  | "sticker"
  | "luggage-tag"
  | "pop-sticker"

export type ProductRecord = {
  id: string
  handle: string
  title: string
  tagline: string
  description: string
  price: number
  category: ProductCategory
  themes: string[]
  isHero?: boolean
  isNew?: boolean
  isBestSeller?: boolean
  isSoldOut?: boolean
}

export const allProducts: ProductRecord[] = [
  // ─── HERO PRODUCTS (7 with full PDP copy, brand-defining) ───
  {
    id: "hero-001",
    handle: "bullshit-remover-enamel-pin",
    title: "Bullshit Remover Lapel Pin",
    tagline: "For the person who has already written off small talk.",
    description: "For the person who has already written off small talk as a waste of time. This pin filters out nonsense — wear it on your jacket, your bag, your tote. It's a conversation starter, a conversation ender, and a very small statement that does a lot of heavy lifting. Enamel. 1 inch. One strong opinion included.",
    price: 249,
    category: "lapel-pin",
    themes: ["sassy", "humor"],
    isHero: true,
    isBestSeller: true,
  },
  {
    id: "hero-002",
    handle: "no-chill-full-card-sticker",
    title: '"No Chill" Card Sticker — Full Card',
    tagline: "For anyone who has handed over their debit card and thought: this could say more.",
    description: "For everyone who has ever handed over their debit card and thought: this could say something more interesting about me. Full credit card size. Matte finish. Slips into your wallet, your phone case, or your ID badge holder. Makes every transaction a tiny personal statement.",
    price: 199,
    category: "card-sticker",
    themes: ["sassy", "humor"],
    isHero: true,
    isBestSeller: true,
  },
  {
    id: "hero-003",
    handle: "no-chill-half-card-sticker",
    title: '"No Chill" Card Sticker — Half Card',
    tagline: "For the person who wants to make a statement but keep it subtle.",
    description: "For the person who wants to make a statement but keep it subtle. Half the size, same amount of opinion. Fits on your Metro card, your office ID, your library card — anything you swipe, tap, or show. Same matte finish. Same energy. Less commitment.",
    price: 149,
    category: "card-sticker",
    themes: ["sassy", "humor"],
    isHero: true,
  },
  {
    id: "hero-004",
    handle: "idiot-repellent-keychain",
    title: "Idiot Repellent Keychain",
    tagline: "For the person whose patience for nonsense is running low.",
    description: "For the person whose patience for nonsense is a finite resource that is currently running very low. Clip it to your keys, your bag, your jeans — let it do the filtering before you have to. Stainless steel. 3 inches. Repels idiots effectively (results may vary).",
    price: 249,
    category: "keychain",
    themes: ["sassy", "humor"],
    isHero: true,
    isBestSeller: true,
  },
  {
    id: "hero-005",
    handle: "enjoy-the-shitshow-fridge-magnet",
    title: '"Enjoy the ShitShow" Fridge Magnet',
    tagline: "For the kitchen that belongs to someone who has accepted the current situation.",
    description: "For the kitchen that belongs to someone who has accepted the current situation with a kind of dark clarity. Sticks to your fridge, your whiteboard, your metal shelf. It's a daily reminder that sometimes you just have to watch it all unfold with a cup of coffee in your hand.",
    price: 149,
    category: "fridge-magnet",
    themes: ["sassy", "humor"],
    isHero: true,
    isBestSeller: true,
  },
  {
    id: "hero-006",
    handle: "enjoy-the-shitshow-drop-earrings",
    title: '"Enjoy the ShitShow" Drop Earrings',
    tagline: "For the person who wants their jewellery to match their personality.",
    description: "For the person who wants their jewellery to match their personality, not just their outfit. Drop earrings with a point of view. Lightweight acrylic. Gold-toned hooks. Wear them to brunch, wear them to work, wear them to family dinners — watch people try to figure out if they should laugh or be concerned.",
    price: 299,
    category: "earring",
    themes: ["sassy", "humor"],
    isHero: true,
  },
  {
    id: "hero-007",
    handle: "birthday-box-bundle",
    title: "The Birthday Box",
    tagline: "For the friend who has everything except something this specific.",
    description: "The Birthday Box. For the friend who has everything except something this specific. 2 enamel pins + 1 keychain + 1 card sticker + gift-ready packaging. Thoughtful, specific, and requires zero wrapping paper skills. Just add a note (optional but recommended).",
    price: 699,
    category: "lapel-pin",
    themes: ["gift"],
    isHero: true,
  },

  // ─── LAPEL PINS (₹149-₹249) ───
  {
    id: "lp-001",
    handle: "nike-air-red-offwhite-lapel-pin",
    title: "Nike Air Red Offwhite Lapel Pin",
    tagline: "Sneaker culture on your collar.",
    description: "Iconic Nike Air silhouette in red offwhite. For sneakerheads who want to rep their culture even when they're not in kicks. Enamel pin, 1 inch, rubber clutch back.",
    price: 149,
    category: "lapel-pin",
    themes: ["sneakerheads", "pop-culture"],
    isBestSeller: true,
  },
  {
    id: "lp-002",
    handle: "smokers-access-lapel-pin",
    title: "Smokers Access Lapel Pin",
    tagline: "Access granted. Opinion included.",
    description: "A lapel pin that says more than just 'I accessorize.' For the person who believes accessories are a form of communication. Enamel, 1 inch.",
    price: 249,
    category: "lapel-pin",
    themes: ["sassy", "humor"],
  },
  {
    id: "lp-003",
    handle: "boss-babe-lapel-pin",
    title: "Boss Babe Lapel Pin",
    tagline: "The boardroom called. They want their boss back.",
    description: "For the woman who runs the show. Whether it's a corner office or a corner desk, this pin claims your territory. Enamel pin, 1 inch.",
    price: 249,
    category: "lapel-pin",
    themes: ["sassy", "design"],
  },
  {
    id: "lp-004",
    handle: "girl-power-lapel-pin",
    title: "Girl Power Lapel Pin",
    tagline: "Feminism. On a pin.",
    description: "Classic girl power energy in enamel form. Wear it on your denim jacket, your tote bag, your conference badge. A tiny reminder that the future is female.",
    price: 249,
    category: "lapel-pin",
    themes: ["sassy", "design"],
    isBestSeller: true,
  },
  {
    id: "lp-005",
    handle: "chill-pill-lapel-pin",
    title: "Chill Pill Lapel Pin",
    tagline: "Take one. Wear it. Feel better.",
    description: "A prescription for relaxation in pin form. For the person who needs a reminder to breathe, preferably attached to their outfit where everyone can see it.",
    price: 249,
    category: "lapel-pin",
    themes: ["humor", "sassy"],
  },
  {
    id: "lp-006",
    handle: "selflove-sauce-lapel-pin",
    title: "Selflove Sauce Lapel Pin",
    tagline: "The secret ingredient is you.",
    description: "Self-love is the best love. And now it's on a pin. Because you deserve to wear your affirmations where everyone can see them.",
    price: 249,
    category: "lapel-pin",
    themes: ["design", "sassy"],
  },
  {
    id: "lp-007",
    handle: "social-anxiety-lapel-pin",
    title: "Social Anxiety Lapel Pin",
    tagline: "I came. I saw. I made eye contact and regretted it.",
    description: "For everyone who rehearses conversations in the shower. A pin that tells people you're not ignoring them — you're just socialising in your head.",
    price: 249,
    category: "lapel-pin",
    themes: ["humor", "sassy"],
  },
  {
    id: "lp-008",
    handle: "shit-happens-lapel-pin",
    title: "Shit Happens Lapel Pin",
    tagline: "Life. On a pin.",
    description: "The universal truth, now available in enamel. For bad days, good days, and the days when you just need everyone to know that you are aware.",
    price: 249,
    category: "lapel-pin",
    themes: ["humor", "sassy"],
  },
  {
    id: "lp-009",
    handle: "straight-outta-fks-to-give-pin",
    title: "Straight Outta F*ks to Give Lapel Pin",
    tagline: "A very clear statement of current inventory levels.",
    description: "A lapel pin for when your give-a-damn is broken. Zero f*ks. One pin. Infinite applications.",
    price: 249,
    category: "lapel-pin",
    themes: ["humor", "sassy"],
  },
  {
    id: "lp-010",
    handle: "easily-distracted-by-dogs-pin",
    title: "Easily Distracted by Dogs Lapel Pin",
    tagline: "A confession, not a complaint.",
    description: "For the person who will cross the street for a puppy. Wear it so people know why you stopped paying attention mid-sentence.",
    price: 249,
    category: "lapel-pin",
    themes: ["animals", "humor"],
  },
  {
    id: "lp-011",
    handle: "always-tired-lapel-pin",
    title: "Always Tired Lapel Pin",
    tagline: "Not lazy. Conserving energy.",
    description: "A mood on a pin. For the perpetually exhausted, the chronically napping, and the 'I'll do it tomorrow' crowd.",
    price: 249,
    category: "lapel-pin",
    themes: ["humor"],
  },
  {
    id: "lp-012",
    handle: "less-panic-more-disco-pin",
    title: "Less Panic More Disco Lapel Pin",
    tagline: "Good advice for any situation.",
    description: "Therapy meets dance floor. Wear it when you need a reminder that sometimes the best response to a crisis is a good beat.",
    price: 249,
    category: "lapel-pin",
    themes: ["music", "sassy"],
  },
  {
    id: "lp-013",
    handle: "sneaker-collection-lapel-pin",
    title: "Sneaker Collection Lapel Pin",
    tagline: "Kicks you can keep on.",
    description: "For the sneakerheads. When you can't wear your grails, wear this. Enamel pin celebrating sneaker culture.",
    price: 249,
    category: "lapel-pin",
    themes: ["sneakerheads", "pop-culture"],
  },
  {
    id: "lp-014",
    handle: "coffee-lapel-pin",
    title: "Coffee Lapel Pin",
    tagline: "Brew-tiful.",
    description: "For the person whose personality is 80% caffeine. A tiny tribute to the bean that makes modern life possible.",
    price: 249,
    category: "lapel-pin",
    themes: ["food", "design"],
  },
  {
    id: "lp-015",
    handle: "cat-yin-yang-lapel-pin",
    title: "Cat Yin and Yang Lapel Pin",
    tagline: "Balance. But make it cats.",
    description: "Yin and yang, reimagined with cats. Because balance is important — and so are cats.",
    price: 249,
    category: "lapel-pin",
    themes: ["animals", "design"],
  },
  {
    id: "lp-016",
    handle: "always-sleepy-cat-club-pin",
    title: "Always Sleepy Cat Club Lapel Pin",
    tagline: "Member since birth.",
    description: "Official membership pin for the Always Sleepy Cat Club. Requirements: own a cat, or be a cat, or just really love naps.",
    price: 249,
    category: "lapel-pin",
    themes: ["animals", "humor"],
  },

  // ─── KEYCHAINS (₹199-₹249) ───
  {
    id: "kc-001",
    handle: "coca-cola-keychain",
    title: "Coca Cola Keychain",
    tagline: "The real thing. On your keys.",
    description: "Classic Coca Cola branding in keychain form. For fans of the drink, the brand, or just the color red. Stainless steel, 2.5 inches.",
    price: 199,
    category: "keychain",
    themes: ["pop-culture", "retro"],
    isBestSeller: true,
  },
  {
    id: "kc-002",
    handle: "suck-it-keychain",
    title: "Suck It Keychain",
    tagline: "Short. Sweet. To the point.",
    description: "A keychain for the person who has one response to most situations: a very direct two words. Stainless steel.",
    price: 199,
    category: "keychain",
    themes: ["sassy", "humor"],
  },
  {
    id: "kc-003",
    handle: "always-tired-keychain",
    title: "Always Tired Keychain",
    tagline: "Carry your mood with you.",
    description: "For the person who is always tired. On your keys, it's a daily reminder that sleep is a dream you haven't caught up to yet.",
    price: 199,
    category: "keychain",
    themes: ["humor"],
  },
  {
    id: "kc-004",
    handle: "girl-power-keychain",
    title: "Girl Power Keychain",
    tagline: "Feminism on a keyring.",
    description: "Girl power energy you can carry everywhere. Clip it, jingle it, show it off. Because equality isn't a trend.",
    price: 199,
    category: "keychain",
    themes: ["sassy", "design"],
  },
  {
    id: "kc-005",
    handle: "himym-keychain",
    title: "HIMYM Keychain",
    tagline: "Legend — wait for it — ary.",
    description: "For the fans who know that 'Pulling a Ted' is a real thing and 'Challenge Accepted' is a valid life philosophy.",
    price: 199,
    category: "keychain",
    themes: ["pop-culture", "tv-movies"],
  },
  {
    id: "kc-006",
    handle: "cat-yin-yang-keychain",
    title: "Cat Yin and Yang Keychain",
    tagline: "Duality. But cat-shaped.",
    description: "The eternal dance of opposing forces, now featuring cats. Because the universe is balanced — and so are your keys.",
    price: 199,
    category: "keychain",
    themes: ["animals", "design"],
  },
  {
    id: "kc-007",
    handle: "world-in-a-bottle-keychain",
    title: "World in a Bottle Keychain",
    tagline: "The whole world. In your pocket.",
    description: "A tiny universe on your keychain. For the dreamers, the travelers, and the people who want to carry the world with them.",
    price: 199,
    category: "keychain",
    themes: ["travel", "design"],
  },
  {
    id: "kc-008",
    handle: "rolling-stones-keychain",
    title: "Rolling Stones Keychain",
    tagline: "Sympathy for the keychain.",
    description: "The Rolling Stones tongue and lips. Because some logos are so iconic they belong on everything — including your keys.",
    price: 199,
    category: "keychain",
    themes: ["music", "pop-culture"],
  },
  {
    id: "kc-009",
    handle: "bibliophile-keychain",
    title: "Bibliophile Keychain",
    tagline: "For the person who always has a book nearby.",
    description: "A keychain for the people who still believe in the smell of paper. Book lovers, this one's yours.",
    price: 199,
    category: "keychain",
    themes: ["books", "design"],
  },
  {
    id: "kc-010",
    handle: "homer-simpson-beer-keychain",
    title: "Homer Simpson's Beer Keychain",
    tagline: "D'oh!",
    description: "Homer Simpson's favourite beer. Duff-branded keychain for Simpsons fans who appreciate the finer things in life.",
    price: 199,
    category: "keychain",
    themes: ["tv-movies", "pop-culture"],
  },
  {
    id: "kc-011",
    handle: "idiot-repellent-keychain-keychain",
    title: "Idiot Repellent Keychain",
    tagline: "Repels idiots. Attracts opinions.",
    description: "Same attitude. Different format. For the person who needs backup on their keys too.",
    price: 249,
    category: "keychain",
    themes: ["sassy", "humor"],
    isBestSeller: true,
  },
  {
    id: "kc-012",
    handle: "always-hungry-keychain",
    title: "Always Hungry Keychain",
    tagline: "Snack enthusiast.",
    description: "For the person whose stomach is on a different timezone than everyone else's. A keychain for the perpetually peckish.",
    price: 199,
    category: "keychain",
    themes: ["food", "humor"],
  },
  {
    id: "kc-013",
    handle: "sneaker-collection-keychain",
    title: "Sneaker Collection Keychain",
    tagline: "Kicks for your keys.",
    description: "Sneaker culture meets keychain culture. For the person whose shoe collection rivals their personality.",
    price: 199,
    category: "keychain",
    themes: ["sneakerheads"],
  },

  // ─── FRIDGE MAGNETS (₹149-₹225) ───
  {
    id: "fm-001",
    handle: "arsenal-fridge-magnet",
    title: "Arsenal Fridge Magnet",
    tagline: "COYG.",
    description: "Show your Arsenal pride even when the fridge is the only thing you're defending. Magnet. 2 inches.",
    price: 225,
    category: "fridge-magnet",
    themes: ["sports"],
  },
  {
    id: "fm-002",
    handle: "serotonin-spray-fridge-magnet",
    title: "Serotonin Spray Fridge Magnet",
    tagline: "One spray. One smile.",
    description: "When you need a hit of happiness between meals. Stick it on your fridge and pretend you're spraying joy directly into your kitchen.",
    price: 225,
    category: "fridge-magnet",
    themes: ["design", "humor"],
  },
  {
    id: "fm-003",
    handle: "morty-fridge-magnet",
    title: "Morty Fridge Magnet",
    tagline: "Aw jeez.",
    description: "Rick and Morty's favourite grandson, now on your fridge. For the part of you that panics about everything but shows up anyway.",
    price: 225,
    category: "fridge-magnet",
    themes: ["tv-movies", "pop-culture"],
  },
  {
    id: "fm-004",
    handle: "rick-fridge-magnet",
    title: "Rick Fridge Magnet",
    tagline: "Wubba lubba dub dub.",
    description: "The smartest man in the universe, holding your grocery list in place. For the part of you that's too intelligent for small talk.",
    price: 225,
    category: "fridge-magnet",
    themes: ["tv-movies", "pop-culture"],
  },
  {
    id: "fm-005",
    handle: "boy-tears-fridge-magnet",
    title: "Boy Tears Fridge Magnet",
    tagline: "Collectible. Emotional.",
    description: "A curated collection of boy tears, preserved in magnet form. For the fridge that's seen some things.",
    price: 225,
    category: "fridge-magnet",
    themes: ["humor", "sassy"],
  },
  {
    id: "fm-006",
    handle: "coca-cola-fridge-magnet",
    title: "Coca Cola Fridge Magnet",
    tagline: "The pause that refreshes.",
    description: "Classic Coca Cola branding. Because your fridge deserves some brand recognition too.",
    price: 225,
    category: "fridge-magnet",
    themes: ["pop-culture", "retro"],
  },
  {
    id: "fm-007",
    handle: "enjoy-the-shitshow-magnet",
    title: '"Enjoy the ShitShow" Fridge Magnet',
    tagline: "Daily reminder. Darkly optimistic.",
    description: "Sometimes you just have to watch it all unfold with a cup of coffee. This magnet keeps you grounded when the chaos hits.",
    price: 149,
    category: "fridge-magnet",
    themes: ["humor", "sassy"],
    isHero: true,
  },
  {
    id: "fm-008",
    handle: "world-on-fire-fridge-magnet",
    title: "World on Fire Fridge Magnet",
    tagline: "Everything is fine.",
    description: "A magnet for the current state of affairs. Stare at it while you wait for your toast to pop. Very on-brand for 2025.",
    price: 199,
    category: "fridge-magnet",
    themes: ["humor", "sassy"],
  },
  {
    id: "fm-009",
    handle: "vitamin-sea-fridge-magnet",
    title: "Vitamin Sea Fridge Magnet",
    tagline: "Prescribed: one ocean, daily.",
    description: "For the person whose happy place is the beach. A tiny dose of Vitamin Sea on your fridge until you can get to the real thing.",
    price: 199,
    category: "fridge-magnet",
    themes: ["travel", "design"],
  },
  {
    id: "fm-010",
    handle: "monday-morning-fridge-magnet",
    title: "Monday Morning Fridge Magnet",
    tagline: "The most relatable magnet you'll ever own.",
    description: "A magnet that captures the exact energy of a Monday morning. (Spoiler: it's not enthusiasm.)",
    price: 199,
    category: "fridge-magnet",
    themes: ["humor"],
  },

  // ─── EARRINGS (₹199-₹299) ───
  {
    id: "er-001",
    handle: "less-panic-more-disco-earrings",
    title: "Less Panic More Disco Earrings",
    tagline: "Dance therapy, earring edition.",
    description: "Drop earrings with the best life advice you'll ever wear. Lightweight. Gold-toned hooks. 2 inches.",
    price: 199,
    category: "earring",
    themes: ["music", "sassy"],
  },
  {
    id: "er-002",
    handle: "ice-cream-love-bites-earrings",
    title: "Ice Cream Love Bites Earrings",
    tagline: "Sweet. With a bite.",
    description: "Ice cream earrings with a love bite twist. For the person whose love language includes dessert.",
    price: 199,
    category: "earring",
    themes: ["food", "cutesy"],
  },
  {
    id: "er-003",
    handle: "cola-earrings",
    title: "Cola Earrings",
    tagline: "Fizzy. Fun. Fabulous.",
    description: "Mini cola bottle earrings. For the person who believes soda is a personality trait.",
    price: 199,
    category: "earring",
    themes: ["food", "pop-culture"],
  },
  {
    id: "er-004",
    handle: "cute-peach-earrings",
    title: "Cute Peach Earrings",
    tagline: "You're a peach.",
    description: "Peach-shaped drop earrings. Cute, juicy, and guaranteed to make people smile.",
    price: 199,
    category: "earring",
    themes: ["cutesy", "food"],
  },
  {
    id: "er-005",
    handle: "sushi-earrings",
    title: "Sushi Earrings",
    tagline: "Wasabi warning.",
    description: "Sushi-shaped drop earrings. For the sushi lover who wants to accessorize their obsession.",
    price: 199,
    category: "earring",
    themes: ["food", "cutesy"],
  },
  {
    id: "er-006",
    handle: "hot-stuff-earrings",
    title: "Hot Stuff Earrings",
    tagline: "Warning: contents are hot.",
    description: "Hot sauce bottle drop earrings. For the person who adds spice to every room they walk into.",
    price: 199,
    category: "earring",
    themes: ["food", "sassy"],
  },
  {
    id: "er-007",
    handle: "world-in-a-bottle-earrings",
    title: "World in a Bottle Earrings",
    tagline: "The universe. On your ears.",
    description: "Tiny world-in-a-bottle drop earrings. For the wanderer who can't travel right now but can accessorize.",
    price: 199,
    category: "earring",
    themes: ["travel", "design"],
  },
  {
    id: "er-008",
    handle: "vacation-in-a-bottle-earrings",
    title: "Vacation in a Bottle Earrings",
    tagline: "Escape plan on your ears.",
    description: "Vacation vibes in bottle form. For the person whose passport is gathering dust but their spirit is still travelling.",
    price: 199,
    category: "earring",
    themes: ["travel", "design"],
  },
  {
    id: "er-009",
    handle: "unicorn-earrings",
    title: "Unicorn Earrings",
    tagline: "Sparkle. Magic. Earrings.",
    description: "Unicorn-shaped drop earrings. Because every outfit could use a little more magic.",
    price: 199,
    category: "earring",
    themes: ["cutesy", "design"],
  },
  {
    id: "er-010",
    handle: "enjoy-the-shitshow-earrings",
    title: '"Enjoy the ShitShow" Drop Earrings',
    tagline: "Your personality, now on your ears.",
    description: "Darkly delightful drop earrings for the person who's accepted the chaos. Lightweight acrylic with gold-toned hooks.",
    price: 299,
    category: "earring",
    themes: ["sassy", "humor"],
    isHero: true,
  },
  {
    id: "er-011",
    handle: "rainbow-earrings",
    title: "Rainbow Earrings",
    tagline: "Pride. Joy. Colour.",
    description: "Rainbow drop earrings. For every day that deserves a splash of colour.",
    price: 299,
    category: "earring",
    themes: ["design", "cutesy"],
  },
  {
    id: "er-012",
    handle: "rolling-stones-earrings",
    title: "Rolling Stones Earrings",
    tagline: "Sympathy for the earrings.",
    description: "The iconic tongue and lips. Now on your ears. Rock and roll never looked so good.",
    price: 299,
    category: "earring",
    themes: ["music", "pop-culture"],
  },

  // ─── CARD STICKERS (₹109-₹199) ───
  {
    id: "cs-001",
    handle: "cartoon-network-card-sticker",
    title: "Cartoon Network Card Sticker",
    tagline: "Nostalgia. In your wallet.",
    description: "Cartoon Network branding in credit card format. Slip it into your wallet for a hit of Saturday morning nostalgia every time you pay.",
    price: 149,
    category: "card-sticker",
    themes: ["pop-culture", "cartoons"],
  },
  {
    id: "cs-002",
    handle: "rich-af-card-sticker",
    title: "Rich AF Card Sticker",
    tagline: "Fake it till you become it.",
    description: "Full credit card sticker that makes a statement every time you pull out your wallet. High-quality matte vinyl.",
    price: 149,
    category: "card-sticker",
    themes: ["sassy", "humor"],
    isBestSeller: true,
  },
  {
    id: "cs-003",
    handle: "shut-up-take-my-money-card-sticker",
    title: "Shut Up & Take My Money Card Sticker",
    tagline: "When you see something you want. And you want it now.",
    description: "The ultimate impulse purchase accessory. Stick it on your card and let your wallet do the talking.",
    price: 149,
    category: "card-sticker",
    themes: ["humor", "sassy"],
  },
  {
    id: "cs-004",
    handle: "stranger-things-card-sticker",
    title: "Stranger Things Card Sticker",
    tagline: "Upside down. Right in your wallet.",
    description: "Stranger Things themed card sticker. For fans of the Demogorgon, Eggos, and everything Hawkins.",
    price: 149,
    category: "card-sticker",
    themes: ["tv-movies", "pop-culture"],
  },
  {
    id: "cs-005",
    handle: "rick-and-morty-portal-card-sticker",
    title: "Rick and Morty Portal Card Sticker",
    tagline: "Wubba lubba dub dub.",
    description: "Portal gun green card sticker. For the Rick and Morty fan who wants their wallet to be interdimensional.",
    price: 149,
    category: "card-sticker",
    themes: ["tv-movies", "pop-culture"],
  },

  // ─── STICKERS (LAPTOP, ₹49-₹99) ───
  {
    id: "st-001",
    handle: "star-wars-sticker",
    title: "Star Wars Sticker",
    tagline: "May the force be with your laptop.",
    description: "Classic Star Wars vinyl sticker. Perfect for laptops, water bottles, notebooks, and any surface that needs a little rebellion.",
    price: 49,
    category: "sticker",
    themes: ["tv-movies", "pop-culture"],
  },
  {
    id: "st-002",
    handle: "sushi-love-sticker",
    title: "Sushi Love Sticker",
    tagline: "Wasabi included.",
    description: "Vinyl sticker for the sushi enthusiast. For laptops, notebooks, and bento boxes.",
    price: 99,
    category: "sticker",
    themes: ["food", "cutesy"],
  },
  {
    id: "st-003",
    handle: "travel-backpack-sticker",
    title: "Travel Backpack Sticker",
    tagline: "Wanderlust. Stick it.",
    description: "Vinyl sticker for the person whose passport is always ready. Slap it on your luggage and let the adventure begin.",
    price: 99,
    category: "sticker",
    themes: ["travel"],
  },
  {
    id: "st-004",
    handle: "peaky-blinders-sticker",
    title: "Peaky Blinders Sticker",
    tagline: "By order of the Peaky Blinders.",
    description: "Vinyl sticker for fans of Thomas Shelby and the Birmingham gang. For your laptop, flask, or flat cap.",
    price: 99,
    category: "sticker",
    themes: ["tv-movies", "pop-culture"],
  },
  {
    id: "st-005",
    handle: "mickey-mouse-sticker",
    title: "Mickey Mouse Sticker",
    tagline: "The OG. On a sticker.",
    description: "Classic Mickey Mouse vinyl sticker. Because some characters never go out of style.",
    price: 99,
    category: "sticker",
    themes: ["cartoons", "pop-culture"],
  },
  {
    id: "st-006",
    handle: "nike-air-sticker",
    title: "Nike Air Sticker",
    tagline: "Just stick it.",
    description: "Nike Air silhouette sticker. For sneakerheads and sportswear fans. Waterproof vinyl.",
    price: 99,
    category: "sticker",
    themes: ["sneakerheads", "pop-culture"],
  },
  {
    id: "st-007",
    handle: "pizza-sticker",
    title: "Pizza Sticker",
    tagline: "A slice of personality.",
    description: "Pizza vinyl sticker. For people who believe pizza is a food group and a personality trait.",
    price: 99,
    category: "sticker",
    themes: ["food", "humor"],
  },
]

export function getProductsByCollection(collectionSlug: string): ProductRecord[] {
  const collectionMap: Record<string, string[]> = {
    "the-loud-ones": ["hero-001", "hero-004", "hero-005", "lp-008", "lp-009", "kc-002", "lp-005", "er-010"],
    "pick-a-side": ["lp-015", "kc-006", "lp-016", "lp-011", "lp-006", "fm-003", "fm-004"],
    "your-energy": ["lp-006", "lp-007", "lp-011", "lp-012", "fm-002", "fm-010", "er-001"],
    "for-the-group-chat": ["kc-005", "lp-003", "kc-001", "cs-004", "cs-005", "st-001", "st-004", "fm-003", "fm-004"],
    "best-sellers": ["hero-001", "hero-004", "hero-005", "lp-001", "lp-004", "kc-001", "kc-011", "cs-002", "fm-007"],
    "new-in": ["lp-016", "kc-013", "er-012", "st-007", "cs-005", "fm-009", "lp-010"],
  }
  const ids = collectionMap[collectionSlug] || []
  return allProducts.filter((p) => ids.includes(p.id))
}

export function getProductsBySet(setSlug: string): ProductRecord[] {
  const setMap: Record<string, string[]> = {
    "the-loud-ones-pack": ["hero-001", "hero-004", "hero-005", "lp-008", "lp-009"],
    "main-character-set": ["lp-004", "lp-006", "lp-013", "kc-004", "fm-002"],
    "no-notes": ["lp-009", "kc-002", "cs-003", "lp-008"],
    "sent-on-read": ["kc-005", "lp-011", "kc-003"],
  }
  const ids = setMap[setSlug] || []
  return allProducts.filter((p) => ids.includes(p.id))
}

export function getProductsByPersona(personaSlug: string): ProductRecord[] {
  const personaMap: Record<string, string[]> = {
    "for-the-one-who-has-no-filter": ["hero-001", "hero-004", "hero-005", "lp-008", "lp-009", "kc-002", "cs-003", "fm-007"],
    "for-the-main-character": ["lp-004", "lp-006", "lp-013", "kc-004", "fm-002", "er-001", "er-009"],
    "for-the-one-always-right": ["lp-005", "lp-012", "kc-003", "kc-005", "fm-002", "fm-010", "er-001"],
    "for-the-impossible-one": ["hero-007", "cs-002", "kc-011", "fm-007", "fm-005"],
  }
  const ids = personaMap[personaSlug] || []
  return allProducts.filter((p) => ids.includes(p.id))
}

export function getLocalProduct(handle: string): ProductRecord | undefined {
  return allProducts.find((p) => p.handle === handle)
}

export function getLocalProducts(): ProductRecord[] {
  return allProducts
}
